name: CI-DEV2

on:
  push:
    branches: [dev]
    

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Project build
      run: |
        docker run ubuntu pwd
